export const ACTIONS = {
  SET_TODOS: "SET_TODOS",
  SET_LOADING: "SET_LOADING",
  ADD_TODO: "ADD_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO: "DELETE_TODO",
  SET_MODAL_DATA: "SET_MODAL_DATA",
  SET_TODO_INPUT: "SET_TODO_INPUT",
  RESET_INPUT: "RESET_INPUT",
  SET_SELECTED_ID: "SET_SELECTED_ID",
};
